#!/usr/bin/env bash

source path-nevigation

run_definition ()
{
    python definition.py
}

make_required_segments ()
{
    [ $# -lt 1 ] \
        && { segments=(*); } \
        || { segments=($@); }
    for segment in ${segments[*]}
    do
        [[ "$segment" != _* ]] \
            && (seg=${segment%/*}; echo "making segment" "$seg"; cd $seg; pwd)
    done
}

cd_from_scr_to_wrapper_dir
cd_into_content_dir
cd_into_segments_dir
make_required_segments $@
